builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ahmetozer/sandal/pkg/cmd.BuildVersion={{.Version}} -X github.com/ahmetozer/sandal/pkg/cmd.BuildCommit={{.Commit}} -X github.com/ahmetozer/sandal/pkg/cmd.BuildDate={{.Date}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
archives:
  - format: gz
    files:
      - none*
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"